sudo: enabled
dist: xenial
language: python
addons:
  postgresql: '10'
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
  firefox: latest
env:
  global:
  - MOZ_HEADLESS=1
  - PGPORT=5432
  - DATABASE_URL=postgres://postgres:@localhost:5432/postgres
python:
- '3.5'
- '3.6'
before_install:
- pip install --upgrade pip
install:
- pip install -r requirements.txt
script:
- "./test.sh"
notifications:
  email:
  - danielrs9705@gmail.com
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: fgqLV72RFWmthED3RGPb7CliuBPmubhLE2MgK3e9qVXByZ/JLV+WYKLQUV3kl3hMyQekKn3OdpgL7TG/Jd9cpX/ptns46LFfexGyUtQsVbiZpUFZBc3BJXC5XRLPrnc4YrP992RjHP2+SCylgEmvvrbrcd/utnEJ2RL6nV5ft2twOxfJpbXuPN2vs/bKRJuLvb+RUv2rZ3n51sBl/DZEnnG3vhZCCIbT1AvI5mtHl9HSXzapdKMHJ2GHf5XIebdal2Qq8KiHn7FWoPSmpFo8nxQCv8pWFGPNXaCVhh2ifs8QeFDFJGjaRQdb/Va9522uFO06N3lMS80B7eBEhJxQF1w5kZITXc+cIb8EgkKqi+50IkWIJpo1JcqlLlq/1shB0zVModqrVD6Mbyj/HVSSeZ4OwIvGvNQOhYCjpUnioaZN1YF66cQKd1h2dsUMHR0pDYnc0GCxmo14U0SKjgrPzHE+8G2ZeSwubf7opJ31MEdN5Kz+tPAbkqnGS7yrP30OAeWgPviUfKuenNYiQwzQ1rEkBV0gvvA6F87WgjbcmNkRl0pEBm8yYPB7Oxf4LhjBLJo2obJx7oNdjpKqOalOHyZvSXReiOkNlarFoWdHHVzS7/Om0ZB/A8kgWkF3XsE9C8F2uLJCh/XvZ4V+zXUwCYOvrW6AeFV97F6g3AoXlss=
  app: crucitafashion-api
  on:
    repo: danielrs975/sistema_crucita_fashion
    python: '3.6'
  skip_cleanup: true
