# Generated by Django 2.1.5 on 2019-01-20 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=500, unique=True)),
                ('costo_total', models.FloatField()),
                ('fecha', models.DateField()),
                ('hora', models.DateTimeField()),
                ('producto', models.ManyToManyField(to='inventario.Producto')),
            ],
        ),
    ]
